### ISSUE TITLE
Is it possible to install only select themes rather than all the supported ones?

### ISSUE THREAD

**Issue by cyfrost** [tliron/install-gnome-themes#33] opened 2019-05-05 17:51 UTC
Hi, This is a great project and the efforts are much celebrated. Recently I've come over an issue and want to share it here to get some help.

By the nature of this script, it installs all the available themes (30+ maybe?) on to the user's system and so the installation (git pull + rendering) can take a _very_ long time (especially on some older machines).

But, most of the time, I only need a handful of them and don't need all others to be installed. So I'm looking for a way to make this script install only select themes but there's no immediately obvious way to do that (or maybe I've overlooked something).

Also, would it be possible to, say, assign a UUID for each theme and then have the script install the themes only with specified UUIDs?

Apologies if I'm missing something, any help is appreciated, Thanks!

**Comment by tliron** [comment] 2019-05-05 20:14
Duplicate of #30

**Closed as completed by tliron** 2019-05-05 20:14 UTC
